### ISSUE TITLE
Confusion on how to use properly

### ISSUE THREAD

**Issue by kimjongbing** [hraban/mac-app-util#7]
**Question/Problem**
I have added this to my flakes but I am not sure if the process is meant to be automated & whether the commands like ``mktrampoline`` are meant to exist on the system.

For instance, if I try to do ``mktrampoline`` it will not be recognised or work. I have to do 
``nix run github:hraban/mac-app-util -- mktrampoline /path/to/MyApp.app /Applications/MyApp.app``. 

Am I misunderstanding how mac-app-util works? Right now (rightly or wrongly) I'm under the impression that its either meant to allow access to the mktrampoline commands directly or automatically make the applications installed via nix searchable by running mktrampoline and other relevant things on them. 

Thank you.

**My flake**
```
{
  description = "Multi-host NixOS and nix-darwin configuration";

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    # Home manager
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Chaotic nyx repository
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable";

    # Solaar (logitech mouse software)
    solaar.url = "https://flakehub.com/f/Svenum/Solaar-Flake/*.tar.gz";

    # Nixvim 
    nixvim.url = "github:nix-community/nixvim";
    nixvim.inputs.nixpkgs.follows = "nixpkgs";

    # Custom preconfigured nixvim setup
    nvix.url = "github:niksingh710/nvix";
    nvix.inputs.nixpkgs.follows = "nixpkgs";

    # sops-nix, secret management
    sops-nix.url = "github:Mic92/sops-nix";
    sops-nix.inputs.nixpkgs.follows = "nixpkgs";

    # Nix-index-database, queried to suggest packages if not found/installed
    nix-index-database.url = "github:nix-community/nix-index-database";
    nix-index-database.inputs.nixpkgs.follows = "nixpkgs";

    # Collection of packages, using this for ALVR
    lemonake.url = "github:passivelemon/lemonake";
    lemonake.inputs.nixpkgs.follows = "nixpkgs";

    # Nix-Darwin (for macOS)
    darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # nix-homebrew
    nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";

    # Homebrew taps
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };

    # Nh_darwin (nix helper ported to use for darwin)
    nh_darwin.url = "github:ToyVo/nh_darwin";
     
    # This should fix GUI apps installed via nix not showing up anywhere on darwin
    mac-app-util.url = "github:hraban/mac-app-util";
  };

  outputs = { self, nixpkgs, home-manager, nix-index-database, darwin, nh_darwin
    , nix-homebrew, homebrew-core, homebrew-cask, mac-app-util, ... }@inputs:
    let
      inherit (self) outputs;
      systems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      # Function to create a NixOS configuration
      mkNixosConfiguration = { system, hostname, username }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs outputs hostname username; };
          modules = [
            # Enable experimental features for the whole system
            ({ pkgs, ... }: {
              nix = {
                package = pkgs.nixFlakes;
                extraOptions = ''
                  experimental-features = nix-command flakes
                '';
                settings.experimental-features = [ "nix-command" "flakes" ];
              };
            })
            ./hosts/${hostname}
            nix-index-database.nixosModules.nix-index
            {
              nixpkgs = {
                config = { allowUnfree = true; };
                overlays = [
                  outputs.overlays.additions
                  outputs.overlays.modifications
                  outputs.overlays.unstable-packages
                ];
              };
            }
            inputs.chaotic.nixosModules.default
            inputs.solaar.nixosModules.default
            home-manager.nixosModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                users.${username} = import ./home/${username}/home.nix;
                backupFileExtension = "backup";
                extraSpecialArgs = { inherit inputs outputs; };
                sharedModules = [
                  inputs.nixvim.homeManagerModules.nixvim
                  # Enable experimental features for home-manager
                  {
                    home.sessionVariables = {
                      NIX_CONFIG = "experimental-features = nix-command flakes";
                    };
                  }
                ];
              };
            }
            # Add nh configuration for NixOS
            ({ ... }: {
              programs.nh = {
                enable = true;
                clean = {
                  enable = true;
                  dates = "weekly";
                  extraArgs = "--keep 5 --keep-since 14d";
                };
              };
            })
          ];
        };

      # Function to create a nix-darwin configuration
      mkDarwinConfiguration = { system, hostname, username }:
        darwin.lib.darwinSystem {
          inherit system;
          specialArgs = { inherit inputs outputs hostname username; };
          modules = [
            # Enable experimental features for the whole system
            ({ pkgs, lib, ... }: {
              nix = {
                package = lib.mkDefault pkgs.nixFlakes;
                extraOptions = lib.mkDefault ''
                  experimental-features = nix-command flakes
                '';
                settings.experimental-features = [ "nix-command" "flakes" ];
              };
            })
            ./hosts/${hostname}
            home-manager.darwinModules.home-manager
            {
              home-manager = {
                useGlobalPkgs = true;
                useUserPackages = true;
                users.${username} = import ./home/${username}/home.nix;
                extraSpecialArgs = { inherit inputs outputs; };
                backupFileExtension = "backup";
              };
            }
            # nix-homebrew module
            nix-homebrew.darwinModules.nix-homebrew
            {
              nix-homebrew = {
                enable = true;
                enableRosetta = true;
                user = "${username}";
                taps = {
                  "homebrew/homebrew-core" = homebrew-core;
                  "homebrew/homebrew-cask" = homebrew-cask;
                };
                mutableTaps = false;
                autoMigrate = true;
              };
            }
            # Add nh_darwin directly to system packages
            ({ pkgs, configs, inputs, ... }: {
              environment.systemPackages =
                [ inputs.nh_darwin.packages.${system}.default ];
              environment.shellAliases = { nh = "nh_darwin"; }; # this doesnt seem to do anything. i'm setting the alias in fish_darwin instead.
            })
            
            # Add mac-app-util module
            mac-app-util.darwinModules.default

            # Add mac-app-util home-manager module
            {
              home-manager.sharedModules = [
                mac-app-util.homeManagerModules.default
              ];
            }
         ];
        };

    in {
      # My custom packages
      packages =
        forAllSystems (system: import ./pkgs nixpkgs.legacyPackages.${system});

      # Formatter for my nix files
      formatter =
        forAllSystems (system: nixpkgs.legacyPackages.${system}.alejandra);

      # Custom overlays
      overlays = import ./overlays { inherit inputs; };

      # Custom NixOS modules
      nixosModules = import ./modules/nixos;

      # Custom home-manager modules
      homeManagerModules = import ./modules/home-manager;

      # NixOS configurations
      nixosConfigurations = {
        sengoku = mkNixosConfiguration {
          system = "x86_64-linux";
          hostname = "sengoku";
          username = "nadeko";
        };

        kanbaru = mkNixosConfiguration {
          system = "x86_64-linux";
          hostname = "kanbaru";
          username = "suruga";
        };
      };

      # nix-darwin configurations
      darwinConfigurations = {
        araragi = mkDarwinConfiguration {
          system = "aarch64-darwin";
          hostname = "araragi";
          username = "koyomi";
        };
      };

      # Standalone home-manager configuration
      homeConfigurations = {
        "nadeko@sengoku" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
          extraSpecialArgs = { inherit inputs outputs; };
          modules = [
            ./home/nadeko/home.nix
            {
              home = {
                sessionVariables = {
                  NIX_CONFIG = "experimental-features = nix-command flakes";
                };
              };
            }
          ];
        };
        "koyomi@araragi" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.aarch64-darwin;
          extraSpecialArgs = { inherit inputs outputs; };
          modules = [
            ./home/koyomi/home.nix
            {
              home = {
                sessionVariables = {
                  NIX_CONFIG = "experimental-features = nix-command flakes";
                };
              };
            }
          ];
        };
        "suruga@kanbaru" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
          extraSpecialArgs = { inherit inputs outputs; };
          modules = [
            ./home/suruga/home.nix
            {
              home = {
                sessionVariables = {
                  NIX_CONFIG = "experimental-features = nix-command flakes";
                };
              };
            }
          ];
        };
      };
    };
}
```

**Comment by hraban** [comment]
Hi, your config looks fine at a glance, although there's a lot of unrelated info here so I may be overlooking something. It'd be easier to check this config if it were a minimal example containing only mac-app-util.

That being said, the idea is that you just load the module, and that's all, nothing else should be necessary. Once you've done a nix-darwin switch, what do you see in /Applications/... and ~/Applications? Do you see the trampoline directories next to the Nix ones?

**Comment by kimjongbing** [comment]
> Hi, your config looks fine at a glance, although there's a lot of unrelated info here so I may be overlooking something. It'd be easier to check this config if it were a minimal example containing only mac-app-util.
> 
> That being said, the idea is that you just load the module, and that's all, nothing else should be necessary. Once you've done a nix-darwin switch, what do you see in /Applications/... and ~/Applications? Do you see the trampoline directories next to the Nix ones?

Yep I can see both but the expected behaviour doesnt happen for me. Also yea sorry I sent the whole flake since I wasn't sure if there's something in the overall flake that's causing the problem. I'll try figure out why it's not working if it's meant to be like this

**Comment by hraban** [comment]
What expected behavior may I ask?

**Comment by kimjongbing** [comment]
> What expected behavior may I ask?

I can't use commands like ``mktrampoline`` on their own, it is not a recognized command. I have to do ``nix run github:hraban/mac-app-util -- mktrampoline /path/to/MyApp.app /Applications/MyApp.app``

**Comment by hraban** [comment]
That's not what the module is intended for. The module fixes the following problems, quoted from the README:

> Use the home-manager module to "fix" your .app launchers:
>
> - Pinning in Dock works across updates
> - Launch from Spotlight
> - Create .app wrappers for non-app bundle, stand-alone binary programs
>
> Now you can launch Nix-installed apps using only your keyboard, using @@html:<kbd>@@⌘ space@@html:</kbd>@@.

The commands are used internally and automatically to fix that for you. If you want to use those commands directly you'll have to add them to your system installed packages, as with other packages.

P.S.: that first line of the readme isn't entirely up to date; it used to be just a home-manager module, but now it's both a nix-darwin _and_ a home-manager module :)

**Comment by kimjongbing** [comment]
> That's not what the module is intended for. The module fixes the following problems, quoted from the README:
> 
> > Use the home-manager module to "fix" your .app launchers:
> > 
> > * Pinning in Dock works across updates
> > * Launch from Spotlight
> > * Create .app wrappers for non-app bundle, stand-alone binary programs
> > 
> > Now you can launch Nix-installed apps using only your keyboard, using ⌘ space.
> 
> The commands are used internally and automatically to fix that for you. If you want to use those commands directly you'll have to add them to your system installed packages, as with other packages.
> 
> P.S.: that first line of the readme isn't entirely up to date; it used to be just a home-manager module, but now it's both a nix-darwin _and_ a home-manager module :)

I see, so if I installed a nix package, it's meant to show up in my `⌘ space` without manual intervention. When I installed Vesktop this did not happen (so I had to run ``nix run github:hraban/mac-app-util -- mktrampoline /path/to/MyApp.app /Applications/MyApp.app``) but I will try it with another application and let you know how it goes.

**Comment by Kristina-Pianykh** [comment]
> > That's not what the module is intended for. The module fixes the following problems, quoted from the README:
> > > Use the home-manager module to "fix" your .app launchers:
> > > 
> > > * Pinning in Dock works across updates
> > > * Launch from Spotlight
> > > * Create .app wrappers for non-app bundle, stand-alone binary programs
> > > 
> > > Now you can launch Nix-installed apps using only your keyboard, using ⌘ space.
> > 
> > 
> > The commands are used internally and automatically to fix that for you. If you want to use those commands directly you'll have to add them to your system installed packages, as with other packages.
> > P.S.: that first line of the readme isn't entirely up to date; it used to be just a home-manager module, but now it's both a nix-darwin _and_ a home-manager module :)
> 
> I see, so if I installed a nix package, it's meant to show up in my `⌘ space` without manual intervention. When I installed Vesktop this did not happen (so I had to run `nix run github:hraban/mac-app-util -- mktrampoline /path/to/MyApp.app /Applications/MyApp.app`) but I will try it with another application and let you know how it goes.

Have you activated your home-manager after adding the module though? I was confused at first, too, until I saw that the trampoline dir is created triggered by the activation action https://github.com/hraban/mac-app-util/blob/9c6bbe2a6a7ec647d03f64f0fadb874284f59eac/flake.nix#L40-L48

**Comment by kimjongbing** [comment]
> > > That's not what the module is intended for. The module fixes the following problems, quoted from the README:
> > > > Use the home-manager module to "fix" your .app launchers:
> > > > 
> > > > * Pinning in Dock works across updates
> > > > * Launch from Spotlight
> > > > * Create .app wrappers for non-app bundle, stand-alone binary programs
> > > > 
> > > > Now you can launch Nix-installed apps using only your keyboard, using ⌘ space.
> > > 
> > > 
> > > The commands are used internally and automatically to fix that for you. If you want to use those commands directly you'll have to add them to your system installed packages, as with other packages.
> > > P.S.: that first line of the readme isn't entirely up to date; it used to be just a home-manager module, but now it's both a nix-darwin _and_ a home-manager module :)
> > 
> > 
> > I see, so if I installed a nix package, it's meant to show up in my `⌘ space` without manual intervention. When I installed Vesktop this did not happen (so I had to run `nix run github:hraban/mac-app-util -- mktrampoline /path/to/MyApp.app /Applications/MyApp.app`) but I will try it with another application and let you know how it goes.
> 
> Have you activated your home-manager after adding the module though? I was confused at first, too, until I saw that the trampoline dir creation is triggered by the activation action
> 
> https://github.com/hraban/mac-app-util/blob/9c6bbe2a6a7ec647d03f64f0fadb874284f59eac/flake.nix#L40-L48

Yep! This did it for me! Thank you for this. And thank you both of you for the help :smile:

**Comment by hraban** [comment]
Thanks for your input both I see that the documentation isn't clear enough so I'll reopen this ticket as being a bug in the documentation.
