### ISSUE TITLE
_LSOpenURLsWithCompletionHandler() failed with error -54

### ISSUE THREAD

**Issue by jakubrpawlowski** [hraban/mac-app-util#8]
I'm on Sequoia 15.1 and after adding the package and trying to start kitty from Spotlight I get error:
_LSOpenURLsWithCompletionHandler() failed with error -54

<img width="298" alt="image" src="https://github.com/user-attachments/assets/3f4235b6-a1c2-4a58-8b47-27a26155596b">

**Comment by hraban** [comment]
Do you have a reproducible example I can try?

**Comment by kwigley** [comment]
I believe this only happens on macos 15.1
```
❯ sw_vers                                                                                                                                                     
ProductName:            macOS
ProductVersion:         15.1
BuildVersion:           24B83
```
```
❯ open '/nix/store/wiindrplkcj1mn22x6nbl8clpnz7adpm-kitty-0.36.4/Applications/kitty.app/'                                                                     
_LSOpenURLsWithCompletionHandler() failed with error -54.
```

**Comment by jakubrpawlowski** [comment]
Yeah I do believe the only repro is updating to Sequoia 15.1 - it worked fine before, even on 15.1 Beta, but somehow it's now broken in official release and reinstalling does not fix it.

**Comment by kwigley** [comment]
Same here, I think we can follow along over here https://github.com/kovidgoyal/kitty/issues/8006, should be good to close issue in this repo

**Comment by hraban** [comment]
Yeah when I do a bare

```
$ open "$(nix build --no-link --print-out-paths nixpkgs#kitty)/Applications/kitty.app"
```

I get the same error. No mac-app-util involved. I think this is an upstream bug, not a mac-app-util one.

**Comment by hraban** [comment]
I'm going to close this bug as it appears to be an upstream problem. Good luck and feel free to reopen if it's mac-app-util!
